# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.io'
#
# Created: Mon Mar 16 13:57:36 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 460)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 460))
        MainWindow.setMaximumSize(QtCore.QSize(640, 460))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(429, 10, 201, 421))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.generate = QtGui.QPushButton(self.gridLayoutWidget)
        self.generate.setObjectName(_fromUtf8("generate"))
        self.gridLayout.addWidget(self.generate, 1, 0, 1, 1)
        self.settings_tab = QtGui.QTabWidget(self.gridLayoutWidget)
        self.settings_tab.setObjectName(_fromUtf8("settings_tab"))
        self.imgtab = QtGui.QWidget()
        self.imgtab.setObjectName(_fromUtf8("imgtab"))
        self.groupBox = QtGui.QGroupBox(self.imgtab)
        self.groupBox.setGeometry(QtCore.QRect(3, 0, 191, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, 10, 191, 71))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(5, 10, 5, -1)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lab_layout = QtGui.QLabel(self.formLayoutWidget)
        self.lab_layout.setObjectName(_fromUtf8("lab_layout"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lab_layout)
        self.img_layout_choice = QtGui.QComboBox(self.formLayoutWidget)
        self.img_layout_choice.setEditable(False)
        self.img_layout_choice.setObjectName(_fromUtf8("img_layout_choice"))
        self.img_layout_choice.addItem(_fromUtf8(""))
        self.img_layout_choice.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.img_layout_choice)
        self.lab_dataset = QtGui.QLabel(self.formLayoutWidget)
        self.lab_dataset.setObjectName(_fromUtf8("lab_dataset"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lab_dataset)
        self.img_dataset_choice = QtGui.QComboBox(self.formLayoutWidget)
        self.img_dataset_choice.setEditable(False)
        self.img_dataset_choice.setObjectName(_fromUtf8("img_dataset_choice"))
        self.img_dataset_choice.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.img_dataset_choice)
        self.groupBox_2 = QtGui.QGroupBox(self.imgtab)
        self.groupBox_2.setGeometry(QtCore.QRect(3, 100, 191, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 191, 61))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(5, 5, 5, -1)
        self.formLayout_2.setHorizontalSpacing(10)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lab_width = QtGui.QLabel(self.formLayoutWidget_2)
        self.lab_width.setObjectName(_fromUtf8("lab_width"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lab_width)
        self.img_width_choice = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.img_width_choice.setMaximum(1920)
        self.img_width_choice.setSingleStep(10)
        self.img_width_choice.setObjectName(_fromUtf8("img_width_choice"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.img_width_choice)
        self.lab_height = QtGui.QLabel(self.formLayoutWidget_2)
        self.lab_height.setObjectName(_fromUtf8("lab_height"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lab_height)
        self.img_height_choice = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.img_height_choice.setMaximum(1080)
        self.img_height_choice.setObjectName(_fromUtf8("img_height_choice"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.img_height_choice)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 70, 191, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 191, 61))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(5, -1, 5, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lab_rmax = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_rmax.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_rmax.setObjectName(_fromUtf8("lab_rmax"))
        self.gridLayout_2.addWidget(self.lab_rmax, 1, 0, 1, 1)
        self.img_rmin_choice = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.img_rmin_choice.setInputMethodHints(QtCore.Qt.ImhNone)
        self.img_rmin_choice.setMaximum(999999999)
        self.img_rmin_choice.setObjectName(_fromUtf8("img_rmin_choice"))
        self.gridLayout_2.addWidget(self.img_rmin_choice, 0, 1, 1, 1)
        self.lab_rmin = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lab_rmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_rmin.setObjectName(_fromUtf8("lab_rmin"))
        self.gridLayout_2.addWidget(self.lab_rmin, 0, 0, 1, 1)
        self.img_rmax_choice = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.img_rmax_choice.setInputMethodHints(QtCore.Qt.ImhNone)
        self.img_rmax_choice.setMaximum(999999999)
        self.img_rmax_choice.setObjectName(_fromUtf8("img_rmax_choice"))
        self.gridLayout_2.addWidget(self.img_rmax_choice, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.imgtab)
        self.groupBox_4.setGeometry(QtCore.QRect(3, 260, 191, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 191, 91))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(5, -1, 5, -1)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lab_bg = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lab_bg.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_bg.setObjectName(_fromUtf8("lab_bg"))
        self.gridLayout_3.addWidget(self.lab_bg, 0, 0, 1, 1)
        self.lab_fg = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lab_fg.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_fg.setObjectName(_fromUtf8("lab_fg"))
        self.gridLayout_3.addWidget(self.lab_fg, 1, 0, 1, 1)
        self.img_bgcolour_choice = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.img_bgcolour_choice.setObjectName(_fromUtf8("img_bgcolour_choice"))
        self.gridLayout_3.addWidget(self.img_bgcolour_choice, 0, 1, 1, 1)
        self.img_fgcolour_choice = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.img_fgcolour_choice.setObjectName(_fromUtf8("img_fgcolour_choice"))
        self.gridLayout_3.addWidget(self.img_fgcolour_choice, 1, 1, 1, 1)
        self.img_bg_picker = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.img_bg_picker.setObjectName(_fromUtf8("img_bg_picker"))
        self.gridLayout_3.addWidget(self.img_bg_picker, 0, 2, 1, 1)
        self.img_fg_picker = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.img_fg_picker.setObjectName(_fromUtf8("img_fg_picker"))
        self.gridLayout_3.addWidget(self.img_fg_picker, 1, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.settings_tab.addTab(self.imgtab, _fromUtf8(""))
        self.gltab = QtGui.QWidget()
        self.gltab.setObjectName(_fromUtf8("gltab"))
        self.settings_tab.addTab(self.gltab, _fromUtf8(""))
        self.gridLayout.addWidget(self.settings_tab, 0, 0, 1, 1)
        self.visualisation = QtGui.QGraphicsView(self.centralwidget)
        self.visualisation.setGeometry(QtCore.QRect(10, 10, 411, 421))
        self.visualisation.setObjectName(_fromUtf8("visualisation"))
        self.progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(160, 200, 118, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 92, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 92, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progress_bar.setPalette(palette)
        self.progress_bar.setMaximum(0)
        self.progress_bar.setProperty("value", -1)
        self.progress_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_bar.setFormat(_fromUtf8(""))
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.settings_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Prime Visualisation", None))
        self.generate.setText(_translate("MainWindow", "Generate", None))
        self.groupBox.setTitle(_translate("MainWindow", "Visualisation", None))
        self.lab_layout.setText(_translate("MainWindow", "Layout", None))
        self.img_layout_choice.setItemText(0, _translate("MainWindow", "Ulam Spiral", None))
        self.img_layout_choice.setItemText(1, _translate("MainWindow", "Sacks Spiral", None))
        self.lab_dataset.setText(_translate("MainWindow", "Dataset", None))
        self.img_dataset_choice.setItemText(0, _translate("MainWindow", "Primes", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings", None))
        self.lab_width.setText(_translate("MainWindow", "Width", None))
        self.lab_height.setText(_translate("MainWindow", "Height", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Range", None))
        self.lab_rmax.setText(_translate("MainWindow", "Max", None))
        self.lab_rmin.setText(_translate("MainWindow", "Min", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Colours", None))
        self.lab_bg.setText(_translate("MainWindow", "BG", None))
        self.lab_fg.setText(_translate("MainWindow", "FG", None))
        self.img_bgcolour_choice.setText(_translate("MainWindow", "#000000", None))
        self.img_fgcolour_choice.setText(_translate("MainWindow", "#FFFFFF", None))
        self.img_bg_picker.setText(_translate("MainWindow", "Choose", None))
        self.img_fg_picker.setText(_translate("MainWindow", "Choose", None))
        self.settings_tab.setTabText(self.settings_tab.indexOf(self.imgtab), _translate("MainWindow", "Image", None))
        self.settings_tab.setTabText(self.settings_tab.indexOf(self.gltab), _translate("MainWindow", "OpenGL", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

