# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabbed.ui'
#
# Created: Tue May  5 02:17:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.main_tabs = QtGui.QTabWidget(self.centralwidget)
        self.main_tabs.setGeometry(QtCore.QRect(0, 0, 641, 461))
        self.main_tabs.setObjectName(_fromUtf8("main_tabs"))
        self.settings_tab = QtGui.QWidget()
        self.settings_tab.setObjectName(_fromUtf8("settings_tab"))
        self.general_settings = QtGui.QGroupBox(self.settings_tab)
        self.general_settings.setGeometry(QtCore.QRect(10, 10, 221, 411))
        self.general_settings.setObjectName(_fromUtf8("general_settings"))
        self.groupBox_3 = QtGui.QGroupBox(self.general_settings)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 201, 81))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.f_bg_button = QtGui.QToolButton(self.groupBox_3)
        self.f_bg_button.setGeometry(QtCore.QRect(165, 50, 27, 20))
        self.f_bg_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.f_bg_button.setObjectName(_fromUtf8("f_bg_button"))
        self.f_fg_text = QtGui.QLineEdit(self.groupBox_3)
        self.f_fg_text.setGeometry(QtCore.QRect(90, 17, 70, 20))
        self.f_fg_text.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.f_fg_text.setObjectName(_fromUtf8("f_fg_text"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 17, 73, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 75, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.f_bg_text = QtGui.QLineEdit(self.groupBox_3)
        self.f_bg_text.setGeometry(QtCore.QRect(90, 50, 70, 20))
        self.f_bg_text.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.f_bg_text.setObjectName(_fromUtf8("f_bg_text"))
        self.f_fg_button = QtGui.QToolButton(self.groupBox_3)
        self.f_fg_button.setGeometry(QtCore.QRect(165, 17, 27, 20))
        self.f_fg_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.f_fg_button.setObjectName(_fromUtf8("f_fg_button"))
        self.groupBox_4 = QtGui.QGroupBox(self.general_settings)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 140, 201, 81))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.f_height = QtGui.QSpinBox(self.groupBox_4)
        self.f_height.setGeometry(QtCore.QRect(80, 46, 111, 20))
        self.f_height.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.f_height.setMinimum(1)
        self.f_height.setMaximum(1080)
        self.f_height.setProperty("value", 250)
        self.f_height.setObjectName(_fromUtf8("f_height"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(36, 20, 35, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(30, 46, 41, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.f_width = QtGui.QSpinBox(self.groupBox_4)
        self.f_width.setGeometry(QtCore.QRect(80, 20, 111, 20))
        self.f_width.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.f_width.setMinimum(1)
        self.f_width.setMaximum(1920)
        self.f_width.setProperty("value", 250)
        self.f_width.setObjectName(_fromUtf8("f_width"))
        self.groupBox_5 = QtGui.QGroupBox(self.general_settings)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 30, 201, 81))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.f_layout = QtGui.QComboBox(self.groupBox_5)
        self.f_layout.setGeometry(QtCore.QRect(80, 46, 111, 20))
        self.f_layout.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.f_layout.setObjectName(_fromUtf8("f_layout"))
        self.f_layout.addItem(_fromUtf8(""))
        self.f_layout.addItem(_fromUtf8(""))
        self.f_layout.addItem(_fromUtf8(""))
        self.f_layout.addItem(_fromUtf8(""))
        self.f_layout.addItem(_fromUtf8(""))
        self.f_layout.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(33, 46, 41, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.f_graphics = QtGui.QComboBox(self.groupBox_5)
        self.f_graphics.setGeometry(QtCore.QRect(80, 20, 111, 20))
        self.f_graphics.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.f_graphics.setObjectName(_fromUtf8("f_graphics"))
        self.f_graphics.addItem(_fromUtf8(""))
        self.f_graphics.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.generate = QtGui.QPushButton(self.general_settings)
        self.generate.setGeometry(QtCore.QRect(10, 360, 201, 41))
        self.generate.setObjectName(_fromUtf8("generate"))
        self.label_8 = QtGui.QLabel(self.general_settings)
        self.label_8.setGeometry(QtCore.QRect(97, 203, 16, 16))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(self.general_settings)
        self.label_10.setGeometry(QtCore.QRect(97, 249, 16, 16))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.specific_settings = QtGui.QGroupBox(self.settings_tab)
        self.specific_settings.setGeometry(QtCore.QRect(240, 10, 391, 411))
        self.specific_settings.setObjectName(_fromUtf8("specific_settings"))
        self.main_tabs.addTab(self.settings_tab, _fromUtf8(""))
        self.visualisation_tab = QtGui.QWidget()
        self.visualisation_tab.setObjectName(_fromUtf8("visualisation_tab"))
        self.visualisation = QtGui.QGraphicsView(self.visualisation_tab)
        self.visualisation.setGeometry(QtCore.QRect(0, 0, 637, 434))
        self.visualisation.setObjectName(_fromUtf8("visualisation"))
        self.main_tabs.addTab(self.visualisation_tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Prime Visualisation", None))
        self.general_settings.setTitle(_translate("MainWindow", "General", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Colours", None))
        self.f_bg_button.setText(_translate("MainWindow", "...", None))
        self.f_fg_text.setText(_translate("MainWindow", "#000000", None))
        self.label_5.setText(_translate("MainWindow", "Foreground", None))
        self.label_9.setText(_translate("MainWindow", "Background", None))
        self.f_bg_text.setText(_translate("MainWindow", "#FFFFFF", None))
        self.f_fg_button.setText(_translate("MainWindow", "...", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Dimensions", None))
        self.label_3.setText(_translate("MainWindow", "Width", None))
        self.label_4.setText(_translate("MainWindow", "Height", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Primary", None))
        self.f_layout.setItemText(0, _translate("MainWindow", "Ulam Spiral", None))
        self.f_layout.setItemText(1, _translate("MainWindow", "Sacks Spiral", None))
        self.f_layout.setItemText(2, _translate("MainWindow", "Data Cloud", None))
        self.f_layout.setItemText(3, _translate("MainWindow", "Complex Plane", None))
        self.f_layout.setItemText(4, _translate("MainWindow", "Simple Grid", None))
        self.f_layout.setItemText(5, _translate("MainWindow", "Wireframe", None))
        self.label_2.setText(_translate("MainWindow", "Layout", None))
        self.f_graphics.setItemText(0, _translate("MainWindow", "Image (png)", None))
        self.f_graphics.setItemText(1, _translate("MainWindow", "OpenGL", None))
        self.label.setText(_translate("MainWindow", "Graphics", None))
        self.generate.setText(_translate("MainWindow", "Generate", None))
        self.specific_settings.setTitle(_translate("MainWindow", "Specific", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.settings_tab), _translate("MainWindow", "Settings", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.visualisation_tab), _translate("MainWindow", "Visualisation", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open...", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

